name: deploy-container

on:
  push:
    branches: [main]
    paths:
      - "packages/container/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/container

    steps:
      - uses: actions/checkout@v3
      - name: install all depedencies
        run: npm install
      - name: build production file
        run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - name: connect with aws bucket
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ""
